version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - node_modules:/home/node/app/node_modules
    ports:
      - "5432:5432"
    environment:
      - NODE_ENV=development
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
volumes:
  node_modules:
